before_script:
  - apt-get update -y
  - apt-get install -y cppcheck sqlfluff postgresql-client

stages:
  - lint
  - test
  - deploy

lint:
  stage: lint
  script:
    - echo "Running linter for C code..."
    - cppcheck --enable=all --inconclusive --quiet --recursive .
    - echo "Running linter for SQL code..."
    - sqlfluff lint sql/

test:
  stage: test
  variables:
    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  script:
    - docker compose up -d
    - echo "Running SQL tests..."
    - psql -U $POSTGRES_USER -d $POSTGRES_DB -f sql/test_script.sql

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    - git tag -a "v$(date +%Y%m%d%H%M%S)" -m "Tagging successful build"
    - git push origin --tags