services:
  db:
    build: .
    image: sonnyland/postgres-extensions:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./extensions:/extensions_src
      - ./extensions/install-extensions.sh:/docker-entrypoint-initdb.d/install-extensions.sh:ro

volumes:
  postgres_data:
