#include "postgres.h"
#include "fmgr.h"
#include "utils/array.h"
#include "utils/lsyscache.h"
#include "catalog/pg_type.h"
#include "utils/builtins.h"
#include "access/htup_details.h"
#include "utils/typcache.h"
