CREATE FUNCTION hello_world(input_array text[]) 
RETURNS text
AS 'MODULE_PATHNAME', 'hello_world'
LANGUAGE C STRICT;


CREATE FUNCTION subq_csv(record)
RETURNS text
AS 'MODULE_PATHNAME', 'subq_csv'
LANGUAGE C STRICT;

CREATE FUNCTION csvify_sfunc(INTERNAL, VARIADIC "any")
RETURNS INTERNAL
AS 'MODULE_PATHNAME', 'csvify_sfunc'
LANGUAGE C IMMUTABLE;

CREATE FUNCTION csvify_ffunc(INTERNAL)
RETURNS text
AS 'MODULE_PATHNAME', 'csvify_ffunc'
LANGUAGE C IMMUTABLE;

CREATE AGGREGATE csvify (VARIADIC "any") (
    SFUNC = csvify_sfunc,
    STYPE = INTERNAL,
    FINALFUNC = csvify_ffunc
);